version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/app
      - ./build/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: ./build/php-fpm
    volumes:
      - ./api:/var/app
    expose:
      - "9000"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  rpc_server:
    build: ./build/rpc_server
    container_name: rpc_server
    volumes:
      - ./server:/var/app
